/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

import java.awt.*;
import javax.swing.GroupLayout;
import javax.swing.SwingConstants; // Dodano import dla czytelności

/**
 *
 * @author Julianna
 */
public class LeftPanel extends javax.swing.JPanel {

    /**
     * Creates new form leftPanel
     */
    public LeftPanel() {
        initComponents();

        // --- ZMIANA: Podmiana jPanel1 na InsideLeftPanel ---
        Rectangle bounds = jPanel1.getBounds();
        this.remove(jPanel1);
        jPanel1 = new InsideLeftPanel(); // Użycie InsideLeftPanel
        jPanel1.setBounds(bounds);
        this.add(jPanel1);
        this.revalidate();
        this.repaint();
        // Ustawienie LeftPanel jako przezroczysty, aby usunąć rogi
        this.setOpaque(false);

        // --- ZMIANA: Style i Wyśrodkowanie Tekstu w Etykietach ---
        jLabel1.setFont(new java.awt.Font("Arial", Font.BOLD, 40));
        jLabel1.setForeground(Color.WHITE);
        jLabel2.setFont(new java.awt.Font("Arial", Font.BOLD, 20));
        jLabel2.setForeground(Color.WHITE);

        // Wyrównanie tekstu wewnątrz etykiety do środka
        jLabel1.setHorizontalAlignment(SwingConstants.CENTER);
        jLabel2.setHorizontalAlignment(SwingConstants.CENTER); // POPRAWIONE na CENTER
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        // --- ZMIANA: jPanel1 zadeklarowany jako InsideLeftPanel ---
        jPanel1 = new InsideLeftPanel();

        jLabel1.setText("CARDBOARD");

        jLabel2.setText("CLIENT SYSTEM");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        // Ustawiono preferowany rozmiar zgodny z ustawieniami InsideLeftPanel
                        .addGap(0, 191, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 177, Short.MAX_VALUE) // Domyślny rozmiar
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);

        // --- ZMIANA: Wyśrodkowanie HorizontalGroup ---
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                // Elastyczny margines początkowy: wypycha elementy do środka
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)

                                // Grupa, która centuje wszystkie swoje elementy
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        // Zmiana z 246 na DEFAULT_SIZE, aby tekst się nie kropkował
                                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))

                                // Elastyczny margines końcowy
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        // --- KONIEC ZMIANY ---

        // Wyrównanie w pionie pozostaje bez zmian (wyśrodkowanie pionowe jest mniej pożądane)
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(127, 127, 127)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel2)
                                .addContainerGap(283, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // --- ZMIANA: Zmieniona deklaracja pola z JPanel na InsideLeftPanel ---
    private InsideLeftPanel jPanel1;
}